### PR TITLE
Fix scene change animation smoothness by adding a 0.5 wait to the fade in

### PR DESCRIPTION
**Pull request by Andrew-Dickinson**

### CODE REVIEW

**Review by wbostick — CHANGES_REQUESTED** [review]
it's definitely still a bit bugged in the open sea encounter, and doesn't play the fade-in when showing the skip-tutorial screen
https://drive.google.com/file/d/1kB3MgdZQvnDetUlKmjWeSXukIW1fHl2M/view

**Comment by Andrew-Dickinson** [comment]
@wbostick 
The issue you show above seems to be a result of a bug with the ordering of when the camera gets centered on the player vs when the circle gets centered on the camera. Instead of taking the time to fix this in a generic way, an easy hotfix is to just move the camera on top of the player's spawn-point in each level.

I have done so, please confirm that this fixes the camera glitches

**Review by SeyhyunYang — APPROVED** [review]
Looks good

**Review by SeyhyunYang — APPROVED** [review]
Looks good

**Pull request merged**
